### ISSUE TITLE
Several warnings and errors

### ISSUE THREAD

**Issue by Eggbertx** [LordGood/Ponies-Ascendant#1]
The game seems to be running reasonably well, but I see a lot of warnings and errors in the message area. It happens when the map first loads, and I've noticed it happens when I click on a building to be built and select its location
Screenshot:
![screenshot from 2015-07-01 15-21-29](https://cloud.githubusercontent.com/assets/76852/8466278/b4b486a4-2005-11e5-80e3-88ee274585e1.png)

**Comment by Eggbertx** [comment]
I just noticed this only happens when playing as the Pegasi race, or at least it seems that way

**Comment by LordGood** [comment]
Hey Josh,

It looks like a little mistake in the hoplite entity template, It should be
fixed now if you update

Cheers!
